apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"editor":"cbrunotte","run":"hello-minikube"},"name":"hello-minikube","namespace":"default","selfLink":"/api/v1/namespaces/default/services/hello-minikube"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"port-2","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"run":"hello-minikube"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    editor: cbrunotte
    run: hello-minikube
  name: hello-minikube
  selfLink: /api/v1/namespaces/default/services/hello-minikube
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-minikube
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
