eurekaserver:
  image:   johncarnell/tmx-eurekasvr:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8761:8761"
  labels:
    kompose.service.type: nodeport
    project: spmia

configserver:
  image: johncarnell/tmx-confsvr:${BUILD_NAME}
  mem_limit: 1000000000
  ports:
    - "8888:8888"
  links:
    - "eurekaserver:eurekaserver"
  environment:
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    ENCRYPT_KEY:       "IMSYMMETRIC"
  labels:
    kompose.service.type: nodeport
    project: spmia

zuulserver:
  image: johncarnell/tmx-zuulsvr:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "5555:5555"
  links:
    - "eurekaserver:eurekaserver"
    - "configserver:configserver"
  environment:
    PROFILE: "default"
    SERVER_PORT: "5555"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  labels:
    kompose.service.type: nodeport
    project: spmia

licensingservice:
  image: johncarnell/tmx-licensing-service:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8080:8080"
  links:
    - "configserver:configserver"
    - "eurekaserver:eurekaserver"
    - "zuulserver:zuulserver"
    - "kafkaserver:kafkaserver"
    - "authenticationservice:authenticationservice"
    - "database"
  environment:
    PROFILE: "dev"
    SERVER_PORT: "8080"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    KAFKASERVER_URI: "kafkaserver"
    ZKSERVER_URI: "kafkaserver"
    AUTHSERVER_URI:   "http://authenticationservice:8901/user"
    ENCRYPT_KEY:       "IMSYMMETRIC"
  labels:
    kompose.service.type: nodeport
    project: spmia

authenticationservice:
  image: johncarnell/tmx-authentication-service:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8901:8901"
  links:
    - "configserver:configserver"
    - "eurekaserver:eurekaserver"
    - "zuulserver:zuulserver"
    - "database:database"
  environment:
    PROFILE: "dev"
    SERVER_PORT: "8901"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    ENCRYPT_KEY:       "IMSYMMETRIC"
  labels:
    kompose.service.type: nodeport
    project: spmia

organizationservice:
  image: johncarnell/tmx-organization-service:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8085:8085"
  links:
    - "configserver:configserver"
    - "eurekaserver:eurekaserver"
    - "zuulserver:zuulserver"
    - "kafkaserver:kafkaserver"
    - "authenticationservice:authenticationservice"
    - "database:database"
  environment:
    PROFILE: "dev"
    SERVER_PORT: "8085"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    KAFKASERVER_URI: "kafkaserver"
    ZKSERVER_URI: "kafkaserver"
    AUTHSERVER_URI:   "http://authenticationservice:8901/user"
    ENCRYPT_KEY:       "IMSYMMETRIC"
  labels:
    kompose.service.type: nodeport
    project: spmia

kafkaserver:
  image: spotify/kafka
  mem_limit: 1073741824
  ports:
    - 2181:2181
    - 9092:9092
  labels:
    kompose.service.type: nodeport
    project: spmia

database:
  image: postgres:10
  environment:
    POSTGRES_USER:     "postgres_dev"
    POSTGRES_PASSWORD: "p0stgr@s_dev"
    POSTGRES_DB:       "eagle_eye_dev"
  ports:
    - "5432:5432"
  labels:
    kompose.service.type: nodeport
    project: spmia
