apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-database
  labels:
    app: database
    project: {{ .Chart.Name }}
spec:
  selector:
    app: database
    project: {{ .Chart.Name }}
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
