---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    project: spmia
    app: echoserver
spec:
  type: NodePort
  selector:
    project: spmia
    app: echoserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
  labels:
    project: spmia
    app: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: spmia
        app: echoserver
    spec:
      restartPolicy: Always
      containers:
        - image: gcr.io/google_containers/echoserver:1.4
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 8080
