apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: option
        valueFrom:
          configMapKeyRef:
            name: options
            key: key5
