apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-05-10T12:45:31Z"
  generation: 17
  labels:
    app: minio
    chart: minio-2.4.16
    heritage: Tiller
    release: minio
  name: minio
  namespace: minio
  resourceVersion: "125064690"
  selfLink: /apis/apps/v1/namespaces/minio/statefulsets/minio
  uid: 7f041d02-7321-11e9-bf1e-005056b87fb2
spec:
  podManagementPolicy: Parallel
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      release: minio
  serviceName: minio-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        release: minio
      name: minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server http://minio-0.minio-svc.minio.svc.cluster.local/export
          http://minio-1.minio-svc.minio.svc.cluster.local/export http://minio-2.minio-svc.minio.svc.cluster.local/export
          http://minio-3.minio-svc.minio.svc.cluster.local/export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: minio
        - name: MINIO_BROWSER
          value: "on"
        image: minio/minio:RELEASE.2019-05-23T00-29-34Z
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: minio
        ports:
        - containerPort: 9000
          name: service
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: export
        - mountPath: /root/.minio/
          name: minio-config-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: minio
      - emptyDir: {}
        name: minio-config-dir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: export
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
      storageClassName: vsphere-block
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentRevision: minio-5dbcbd67dd
  observedGeneration: 17
  replicas: 0
  updateRevision: minio-5dbcbd67dd
