apiVersion: v1
kind: Service
metadata:
  name: authenticationservice
  labels:
    project: spmia
    app: authenticationservice
spec:
  selector:
    project: spmia
    app: authenticationservice
  type: NodePort
  ports:
    - port: 8901
      targetPort: 8901
      nodePort: 30000
