apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    project: spmia
    app: configserver
spec:
  selector:
    project: spmia
    app: configserver
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001
