apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    project: spmia
    app: database
spec:
  selector:
    project: spmia
    app: database
  type: NodePort
  ports:
    - name: postgres
      # The port inside the POD
      targetPort: 5432
      # The port accessible by other services inside the cluster
      port: 5432
      # The port accessible at $(minikube ip) for types NodePort and Loadbalancer; must be in the range of 30000-32767
      nodePort: 30002
      protocol: TCP

