apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    project: spmia
    app: eurekaserver
spec:
  selector:
    project: spmia
    app: eurekaserver
  type: NodePort
  ports:
    - name: eureka
      port: 8761
      targetPort: 8761
      nodePort: 30003
