apiVersion: v1
kind: Service
metadata:
  name: zuulserver
  labels:
    project: spmia
    app: zuulserver
spec:
  selector:
    project: spmia
    app: zuulserver
  type: NodePort
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 30008
